production: false

database:
  credentials:
    connectionString: mongodb://localhost/namisushi-local
  options:
    useNewUrlParser: true
    useUnifiedTopology: true
    ignoreUndefined: false
    keepAlive: true

server:
  http:
    protocol: http
    address: 127.0.0.1
    host: localhost:8080/api
    port: 8080
  cors:
    allowedOrigins:
      - http://localhost:8000
    allowedHeaders:
      - origin
      - content-type
      - cookie
      - x-real-host
  csp:
    directives:
      defaultSrc: [
        "'self'",
        "'unsafe-inline'",
        "'unsafe-eval'",
        "*.jsdelivr.net",
        "*.googleapis.com",
        "*.gstatic.com",
        "blob:",
        "data:"
      ]
      data: [
        "'unsafe-inline'",
        "'unsafe-eval'",
        "blob:",
        "data:"
      ]


logger:
  # Recommended false for production
  pretty: true
  time: true
  # Recommended false for production
  isoTime: true
  level: debug # debug | info

user:
  session:
    maximum: 10

    cookie:
      path: /
      domain: localhost
      sameSite: strict
      maxAge: 5184000000

  superadmin:
    username: admin
    email: admin@nowhere.org
    password: SuperSecretPassword


telegram:
  token: 0000000000:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

product:
  image:
    maximum: 10
    file:
      allowedTypes: [
        image/jpeg,
        image/png,
        image/jpg
      ]
      maximumSize: 10485760

order:
  discount:
    # Процент скидки от стоимости заказа
    withoutDelivery: 10
    weekday: 15