production: false

database:
  credentials:
    connectionString: mongodb://localhost/namisushi-local
  options:
    useNewUrlParser: true
    useUnifiedTopology: true
    ignoreUndefined: false
    keepAlive: true

server:
  address:
    api: http://localhost:8080
    user: http://localhost:8000
    admin: http://localhost:8001
  http:
    address: 127.0.0.1
    port: 8080
  cors:
    allowedOrigins:
      - http://localhost:8000
    allowedHeaders:
      - origin
      - content-type
      - cookie
      - x-real-host
  csp:
    directives:
      defaultSrc: [
        "'self'",
        "'unsafe-inline'",
        "'unsafe-eval'",
        "*.jsdelivr.net",
        "*.googleapis.com",
        "*.gstatic.com",
        "blob:",
        "data:"
      ]
      data: [
        "'unsafe-inline'",
        "'unsafe-eval'",
        "blob:",
        "data:"
      ]
  telegram:
    token: 0000000000:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    enableWebhook: false
    webhook:
      port: 9000
      hookPath: /api/telegram
      domain: localhost:9000
  ws:
    port: 8000

logger:
  # Recommended false for production
  pretty: true
  time: true
  # Recommended false for production
  isoTime: true
  level: debug # debug | info

user:
  otp:
    debug: true
    providers:
      greenSMS:
        dayLimits:
          phone: 10
          total: 1000
        testMode: true
        token: stub

  session:
    maximum: 10

    cookie:
      path: /
      domain: localhost
      sameSite: strict
      maxAge: 5184000000

  superadmin:
    email: admin@nowhere.org
    password: SuperSecretPassword

  avatar:
    allowedTypes: [
      image/jpeg,
      image/png,
      image/jpg
    ]
    maximumSize: 10485760

product:
  variant:
    icon:
      maximumSize: 10485760
    image:
      allowedTypes: [
        image/jpeg,
        image/png,
        image/jpg,
        image/webp
      ]
      maximumSize: 10485760
  tag:
    icon:
      maximumSize: 10485760
  image:
    maximum: 10
    file:
      allowedTypes: [
        image/jpeg,
        image/png,
        image/jpg,
        image/webp
      ]
      maximumSize: 10485760

order:
  discount:
    # Процент скидки от стоимости заказа
    withoutDelivery: 10
    weekday: 15